# Generated by Django 4.2.3 on 2023-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrmModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("module_id", models.CharField(max_length=50, unique=True)),
                ("module_secret", models.CharField(max_length=50)),
                ("module_url", models.CharField(max_length=255)),
                ("interval", models.IntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enable", models.BooleanField(default=False)),
                ("exporter_url", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
