# Generated by Django 4.2.3 on 2023-09-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grmmodule",
            name="enable",
        ),
        migrations.RemoveField(
            model_name="grmmodule",
            name="exporter_url",
        ),
        migrations.RemoveField(
            model_name="grmmodule",
            name="interval",
        ),
    ]
