# Generated by Django 4.2.3 on 2023-09-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grm", "0002_remove_grmmodule_enable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrmModuleVar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
                ("rw", models.BooleanField(default=False)),
                ("desc", models.CharField(default="", max_length=200)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grm.grmmodule"
                    ),
                ),
            ],
            options={
                "unique_together": {("id", "module")},
            },
        ),
    ]
