# Generated by Django 4.2.3 on 2023-09-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grm", "0005_alter_grmmodulevar_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grmmodulevar",
            name="module",
            field=models.ForeignKey(
                db_column="module_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vars",
                to="grm.grmmodule",
                to_field="module_id",
            ),
        ),
    ]
