# Generated by Django 4.2.3 on 2023-09-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grm", "0006_alter_grmmodulevar_module"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grmmodulevar",
            unique_together={("name", "module")},
        ),
    ]
