# Generated by Django 4.2.3 on 2023-09-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grm", "0007_alter_grmmodulevar_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="grmmodulevar",
            name="local",
            field=models.BooleanField(default=False),
        ),
    ]
