# Generated by Django 4.2.6 on 2023-10-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='sort',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dictdata',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='sort',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
