# Generated by Django 4.2.5 on 2023-10-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0002_alter_menu_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
