# Generated by Django 4.2.5 on 2023-10-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0003_delete_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
