# Generated by Django 4.2.6 on 2023-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0003_alter_department_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sort',
            field=models.IntegerField(default=1),
        ),
    ]
