# Generated by Django 4.2.5 on 2023-10-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_label',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
