# Generated by Django 4.2.5 on 2023-10-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0005_alter_user_gender_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sys.menu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sys.department'),
        ),
    ]
