# Generated by Django 4.2.5 on 2023-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0007_alter_menu_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictdata',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dictdata',
            name='dict_type',
        ),
        migrations.AddField(
            model_name='dictdata',
            name='type_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
