# Generated by Django 4.2.5 on 2023-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_notifymessage_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymessage',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
