# Generated by Django 4.2.5 on 2023-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alter_notifymessage_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymessage',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
