# Generated by Django 4.2.5 on 2023-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alter_notifymessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymessage',
            name='level',
            field=models.CharField(choices=[('default', '默认'), ('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=100),
        ),
    ]
