# Generated by Django 4.2.5 on 2023-09-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('gender_label', models.CharField(max_length=10)),
                ('avatar', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.department')),
                ('role', models.ManyToManyField(to='auth.role')),
            ],
        ),
    ]
