# Generated by Django 4.2.5 on 2023-09-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_department_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rolemenuid',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.role'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('keep_alive', models.BooleanField(default=True)),
                ('role', models.ManyToManyField(to='auth.role')),
            ],
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.dicttype')),
            ],
        ),
    ]
