# Generated by Django 4.2.5 on 2023-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_delete_roleoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='data_scope',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
    ]
