# Generated by Django 4.2.5 on 2023-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_alter_role_create_time_alter_role_data_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
