# Generated by Django 4.2.5 on 2023-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_role_create_time_alter_role_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
