# Generated by Django 4.2.5 on 2023-09-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_role_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='data_scope',
        ),
    ]
