# Generated by Django 4.2.5 on 2023-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_remove_role_data_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
