# Generated by Django 4.2.5 on 2023-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_rename_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
