# Generated by Django 4.2.5 on 2023-10-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_status_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictdata',
            old_name='name',
            new_name='label',
        ),
    ]
