# Generated by Django 4.2.5 on 2023-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_rename_name_dictdata_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictdata',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dictdata',
            name='sort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicttype',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
