# Generated by Django 4.2.5 on 2023-10-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_dictdata_remark_dictdata_sort_dicttype_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicttype',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
