# Generated by Django 4.2.5 on 2023-10-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0002_graph_module_site_variable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=5)),
                ('timeout', models.IntegerField(default=3)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada.module')),
            ],
        ),
    ]
