# Generated by Django 4.2.6 on 2023-11-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0002_module_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('default', '默认'), ('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada.site')),
                ('variables', models.ManyToManyField(null=True, to='scada.variable')),
            ],
        ),
    ]
