# Generated by Django 4.2.5 on 2023-10-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0003_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='scada.module'),
        ),
    ]
