# Generated by Django 4.2.6 on 2023-11-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_alter_sitestatistic_variables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitestatistic',
            unique_together={('name', 'site')},
        ),
    ]
