# Generated by Django 4.2.5 on 2023-10-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_alter_collector_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(max_length=255)),
                ('alert_level', models.CharField(default='none', max_length=255)),
                ('threshold', models.FloatField(default=0.0)),
                ('state', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('duration', models.CharField(default='0s', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='NotifyMessage',
            new_name='Notify',
        ),
    ]
