# Generated by Django 4.2.6 on 2023-11-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0005_alter_sitestatistic_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scada.site')),
            ],
        ),
    ]
