# Generated by Django 4.2.5 on 2023-10-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0005_rule_rename_notifymessage_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='variable_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='variable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scada.variable'),
            preserve_default=False,
        ),
    ]
