# Generated by Django 4.2.5 on 2023-10-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0006_remove_rule_variable_id_rule_variable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('name', 'variable')},
        ),
    ]
