# Generated by Django 4.2.6 on 2023-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0006_sitevideosource'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
