# Generated by Django 4.2.5 on 2023-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0007_alter_rule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(default=30.592849),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(default=114.305215),
        ),
    ]
