# Generated by Django 4.2.5 on 2023-10-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0008_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scada.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
