# Generated by Django 4.2.5 on 2023-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0009_graph_site_alter_graph_name_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='group',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
