# Generated by Django 4.2.5 on 2023-10-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0010_variable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
